export enum GameProgress {
  MATCHING = 'MATCHING',
  COORDINATE = 'COORDINATE',
  CONVENE = 'CONVENE',
  STARTED = 'STARTED',
  ENDED = 'ENDED',
  ENTER_SCORE = 'ENTER_SCORE',
  EXPIRED = 'EXPIRED',
  NA = 'NA',
}
